<a href="https://colab.research.google.com/github/dantls/python-learning/blob/main/Ex1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
from sklearn.linear_model import Perceptron
from sklearn.metrics import mean_absolute_error

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/observ.csv', sep=';')


X=[]
X = np.array(data[:10]["Fechamento"])

dados = []
x_treino = []
x_test = []
y = []
tam_janela = 3

for i in range(0,len(X)-tam_janela): 
   dados.append(X[i:tam_janela+i])
   y.append(X[tam_janela+i])

print(dados)

[array([7252.034668, 7448.307617, 7546.996582]), array([7448.307617, 7546.996582, 7556.237793]), array([7546.996582, 7556.237793, 7564.345215]), array([7556.237793, 7564.345215, 7400.899414]), array([7564.345215, 7400.899414, 7278.119629]), array([7400.899414, 7278.119629, 7217.427246]), array([7278.119629, 7217.427246, 7243.134277])]


In [ ]:
dados

array([[7252.034668, 7448.307617, 7546.996582],
       [7448.307617, 7546.996582, 7556.237793],
       [7546.996582, 7556.237793, 7564.345215],
       [7556.237793, 7564.345215, 7400.899414],
       [7564.345215, 7400.899414, 7278.119629],
       [7400.899414, 7278.119629, 7217.427246],
       [7278.119629, 7217.427246, 7243.134277]])

In [ ]:
y

array([7556.237793, 7564.345215, 7400.899414, 7278.119629, 7217.427246,
       7243.134277, 7269.68457 ])

In [ ]:
dados = np.array(dados)
dados

array([[7252.034668, 7448.307617, 7546.996582],
       [7448.307617, 7546.996582, 7556.237793],
       [7546.996582, 7556.237793, 7564.345215],
       [7556.237793, 7564.345215, 7400.899414],
       [7564.345215, 7400.899414, 7278.119629],
       [7400.899414, 7278.119629, 7217.427246],
       [7278.119629, 7217.427246, 7243.134277]])

In [ ]:
y = np.array(y)
y

array([7556.237793, 7564.345215, 7400.899414, 7278.119629, 7217.427246,
       7243.134277, 7269.68457 ])

In [ ]:
dados.shape

(7, 3)

In [ ]:
y.shape

(7,)

In [ ]:
perceptron = Perceptron()
perceptron.fit(dados,y)

ValueError: ignored

In [ ]:
X_treino



[array([7252.034668, 7448.307617, 7546.996582]),
 array([7448.307617, 7546.996582, 7556.237793]),
 array([7546.996582, 7556.237793, 7564.345215]),
 array([7556.237793, 7564.345215, 7400.899414]),
 array([7564.345215, 7400.899414, 7278.119629])]

In [ ]:
X_treino = dados[:5]
y_treino = y[:5]
X_test = dados[5:]
y_test = y[5:]

In [ ]:
perceptron = Perceptron()

In [ ]:
y_treino

[7556.237793000001,
 7564.345215,
 7400.899414,
 7278.119629000001,
 7217.427245999999]

In [ ]:
y

[7556.237793000001,
 7564.345215,
 7400.899414,
 7278.119629000001,
 7217.427245999999,
 7243.134276999999,
 7269.68457]

In [ ]:
perceptron.fit(dados,y)

ValueError: ignored